#!/bin/bash
#
# graphios      start the graphios script
#
#
# chkconfig: 345 99 01
# description: graphios nagios -> graphite script
#
# File : graphios

# Source function library.
. /etc/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0

prog="/usr/bin/graphios.py"
OPTIONS=""
GRAPHIOS_USER="nagios"
RETVAL=0
lockfile=/var/lock/subsys/graphios

if [ -f /etc/sysconfig/graphios ]; then
	. /etc/sysconfig/graphios
fi

start () {
        echo -n $"Starting $prog: "
        nohup su ${GRAPHIOS_USER} -s /bin/sh -c "${prog} ${OPTIONS}" >/dev/null 2>&1 &
        RETVAL=$?
        [ $RETVAL -eq 0 ] && touch ${lockfile} && success || failure
        echo
}

stop () {
        echo -n $"Stopping $prog: "
        killproc graphios.py
        RETVAL=$?
        [ $RETVAL -eq 0 ] && rm -f ${lockfile}
        echo
}

restart () {
        stop
        start
}


# See how we are called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  status)
        status $prog
        RETVAL=$?
        ;;
  *)
        echo "Usage: service graphios {start|stop|restart|reload}"
        RETVAL=2
        ;;
esac

exit $RETVAL
